openapi: 3.0.0
info:
  description: "This is the sever spec for posepal backend."
  version: 1.0.0
  title: "Posepal Backend API"
paths:
  /api/users/users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                username:
                  type: string
      responses:
        "201":
          description: User created successfully
        "400":
          description: Invalid input
  /api/users/user:
    get:
      summary: Get user information
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                    format: email
                  username:
                    type: string
                  history:
                    type: array
                    items:
                      type: integer
        "401":
          description: Unauthorized
  /api/users/login:
    post:
      summary: Authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        "200":
          description: Login successful
        "401":
          description: Authentication failed
  /api/users/history:
    post:
      summary: Add a new history record
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                duration:
                  type: string
                  format: email
                detection_count:
                  type: string
      responses:
        "200":
          description: User information retrieved successfully
        "401":
          description: Unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
